-- -------------------------------------------------------------------------------
--
-- Copyright © 2020 by Spectades BV
--
-- Filename    : qbz_uds_ouwocf_bot.sql
--
-- Description : Update boilertexts for OUWOCF
--
-- Product     : EAM             Release : 11.7          Build :
--
-- Author      : MCT
--
-- CHANGE HISTORY
--
-- 0001 15-09-2022  - MCT - SPC254  - Creation
-- -------------------------------------------------------------------------------

PROMPT ...Begin of qbz_uds_ouwocf_bot.sql
PROMPT

--uds WC boilertext
PROMPT ...Start of Boierlexts: OUWOCF

UPDATE r5boilertexts SET bot_text = 'List View' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'LST' AND bot_lang = 'EN' and  bot_text <> 'List View';
UPDATE r5boilertexts SET bot_text = 'Description' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_DESCRIPTION' AND bot_lang = 'EN' and  bot_text <> 'Description';
UPDATE r5boilertexts SET bot_text = 'Sequence No' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_SEQ' AND bot_lang = 'EN' and  bot_text <> 'Sequence No';
UPDATE r5boilertexts SET bot_text = 'Organisation' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_ORG' AND bot_lang = 'EN' and  bot_text <> 'Organisation';
UPDATE r5boilertexts SET bot_text = 'Vendor' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_VEN' AND bot_lang = 'EN' and  bot_text <> 'Vendor';
UPDATE r5boilertexts SET bot_text = 'Status' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_STATUS' AND bot_lang = 'EN' and  bot_text <> 'Status';
UPDATE r5boilertexts SET bot_text = 'Status Desc' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_STADESC' AND bot_lang = 'EN' and  bot_text <> 'Status Desc';
UPDATE r5boilertexts SET bot_text = 'PO Date Generated' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_DATEGEN' AND bot_lang = 'EN' and  bot_text <> 'PO Date Generated';
UPDATE r5boilertexts SET bot_text = 'Created By' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_WCCREATEDBY' AND bot_lang = 'EN' and  bot_text <> 'Created By';
UPDATE r5boilertexts SET bot_text = 'Date Created' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_WCCREATED' AND bot_lang = 'EN' and  bot_text <> 'Date Created';
UPDATE r5boilertexts SET bot_text = 'PO Generated By' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_POCREATEDBY' AND bot_lang = 'EN' and  bot_text <> 'PO Generated By';
UPDATE r5boilertexts SET bot_text = 'Purchase Order' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_PO' AND bot_lang = 'EN' and  bot_text <> 'Purchase Order';
UPDATE r5boilertexts SET bot_text = 'Record View' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'HDR' AND bot_lang = 'EN' and  bot_text <> 'Record View';
UPDATE r5boilertexts SET bot_text = 'Details' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'BLOCK_10_1' AND bot_lang = 'EN' and  bot_text <> 'Details';
UPDATE r5boilertexts SET bot_text = 'WO Details' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'BLOCK_10_2' AND bot_lang = 'EN' and  bot_text <> 'WO Details';
UPDATE r5boilertexts SET bot_text = '<SECTION TITLE>' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'BLOCK_10_3' AND bot_lang = 'EN' and  bot_text <> '<SECTION TITLE>';
UPDATE r5boilertexts SET bot_text = 'Organisation' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'BLOCK_10_CF' AND bot_lang = 'EN' and  bot_text <> 'Organisation';
UPDATE r5boilertexts SET bot_text = '<SECTION TITLE>' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'BLOCK_10_4' AND bot_lang = 'EN' and  bot_text <> '<SECTION TITLE>';
UPDATE r5boilertexts SET bot_text = '<SECTION TITLE>' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'BLOCK_10_5' AND bot_lang = 'EN' and  bot_text <> '<SECTION TITLE>';
UPDATE r5boilertexts SET bot_text = '<SECTION TITLE>' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'BLOCK_10_6' AND bot_lang = 'EN' and  bot_text <> '<SECTION TITLE>';
UPDATE r5boilertexts SET bot_text = 'PO Details' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'BLOCK_10_7' AND bot_lang = 'EN' and  bot_text <> 'PO Details';
UPDATE r5boilertexts SET bot_text = 'Submit' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'GWPSUBMITBUTTON' AND bot_lang = 'EN' and  bot_text <> 'Submit';
UPDATE r5boilertexts SET bot_text = 'Clear' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'GWPCLEARBUTTON' AND bot_lang = 'EN' and  bot_text <> 'Clear';
UPDATE r5boilertexts SET bot_text = 'Description' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_DESCRIPTION' AND bot_lang = 'EN' and  bot_text <> 'Description';
UPDATE r5boilertexts SET bot_text = 'Sequence No' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_SEQ' AND bot_lang = 'EN' and  bot_text <> 'Sequence No';
UPDATE r5boilertexts SET bot_text = 'Organisation' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_ORG' AND bot_lang = 'EN' and  bot_text <> 'Organisation';
UPDATE r5boilertexts SET bot_text = 'Vendor' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_VEN' AND bot_lang = 'EN' and  bot_text <> 'Vendor';
UPDATE r5boilertexts SET bot_text = 'Status' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_STATUS' AND bot_lang = 'EN' and  bot_text <> 'Status';
UPDATE r5boilertexts SET bot_text = 'Status Desc' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_STADESC' AND bot_lang = 'EN' and  bot_text <> 'Status Desc';
UPDATE r5boilertexts SET bot_text = 'PO Date Generated' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_DATEGEN' AND bot_lang = 'EN' and  bot_text <> 'PO Date Generated';
UPDATE r5boilertexts SET bot_text = 'Created By' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_WCCREATEDBY' AND bot_lang = 'EN' and  bot_text <> 'Created By';
UPDATE r5boilertexts SET bot_text = 'Date Created' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_WCCREATED' AND bot_lang = 'EN' and  bot_text <> 'Date Created';
UPDATE r5boilertexts SET bot_text = 'PO Generated By' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_POCREATEDBY' AND bot_lang = 'EN' and  bot_text <> 'PO Generated By';
UPDATE r5boilertexts SET bot_text = 'Purchase Order' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_PO' AND bot_lang = 'EN' and  bot_text <> 'Purchase Order';
UPDATE r5boilertexts SET bot_text = 'Comments' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'CMT' AND bot_lang = 'EN' and  bot_text <> 'Comments';
UPDATE r5boilertexts SET bot_text = 'Documents' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'DOC' AND bot_lang = 'EN' and  bot_text <> 'Documents';
UPDATE r5boilertexts SET bot_text = 'Add Document' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'DOC_ADDNEW' AND bot_lang = 'EN' and  bot_text <> 'Add Document';
UPDATE r5boilertexts SET bot_text = 'Create/Upload Document' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'DOC_CREATEORUPLOADDOCUMENT' AND bot_lang = 'EN' and  bot_text <> 'Create/Upload Document';
UPDATE r5boilertexts SET bot_text = 'Upload Document' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'DOC_UPLOADDOCUMENT' AND bot_lang = 'EN' and  bot_text <> 'Upload Document';
UPDATE r5boilertexts SET bot_text = 'Create Document' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'DOC_CREATEDOCUMENT' AND bot_lang = 'EN' and  bot_text <> 'Create Document';
UPDATE r5boilertexts SET bot_text = 'Documents' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'DOC_DOCDETAILS' AND bot_lang = 'EN' and  bot_text <> 'Documents';
UPDATE r5boilertexts SET bot_text = 'Work Order Check' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'XWO' AND bot_lang = 'EN' and  bot_text <> 'Work Order Check';
UPDATE r5boilertexts SET bot_text = 'Work Order Check' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'XWO_HDRLABEL' AND bot_lang = 'EN' and  bot_text <> 'Work Order Check';
UPDATE r5boilertexts SET bot_text = 'All Records' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'XWO_DSNAME' AND bot_lang = 'EN' and  bot_text <> 'All Records';
UPDATE r5boilertexts SET bot_text = 'Work Order' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'xwo_evtcode' AND bot_lang = 'EN' and  bot_text <> 'Work Order';
UPDATE r5boilertexts SET bot_text = 'Work Order Desc' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'xwo_evtdesc' AND bot_lang = 'EN' and  bot_text <> 'Work Order Desc';
UPDATE r5boilertexts SET bot_text = 'Asset' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'xwo_evtobject' AND bot_lang = 'EN' and  bot_text <> 'Asset';
UPDATE r5boilertexts SET bot_text = 'Licence Plate' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'xwo_objalias' AND bot_lang = 'EN' and  bot_text <> 'Licence Plate';
UPDATE r5boilertexts SET bot_text = 'Date Ready' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'xwo_evtudfdate09' AND bot_lang = 'EN' and  bot_text <> 'Date Ready';
UPDATE r5boilertexts SET bot_text = 'Agree' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'xwo_evtudfchkbox02' AND bot_lang = 'EN' and  bot_text <> 'Agree';
UPDATE r5boilertexts SET bot_text = 'Work Order Status' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'xwo_evtstatus' AND bot_lang = 'EN' and  bot_text <> 'Work Order Status';
UPDATE r5boilertexts SET bot_text = 'Asset Desc' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'xwo_objdesc' AND bot_lang = 'EN' and  bot_text <> 'Asset Desc';
UPDATE r5boilertexts SET bot_text = 'Material Cost' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'xwo_matcost' AND bot_lang = 'EN' and  bot_text <> 'Material Cost';
UPDATE r5boilertexts SET bot_text = 'Fixed Cost' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'xwo_fixedcost' AND bot_lang = 'EN' and  bot_text <> 'Fixed Cost';
UPDATE r5boilertexts SET bot_text = 'Cost Hours' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'xwo_costhours' AND bot_lang = 'EN' and  bot_text <> 'Cost Hours';
UPDATE r5boilertexts SET bot_text = 'Total Cost' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'xwo_totalcost' AND bot_lang = 'EN' and  bot_text <> 'Total Cost';
UPDATE r5boilertexts SET bot_text = 'Code' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_QUERY_WOCORG_ORG_CODE' AND bot_lang = 'EN' and  bot_text <> 'Code';
UPDATE r5boilertexts SET bot_text = 'Description' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_QUERY_WOCORG_ORG_DESC' AND bot_lang = 'EN' and  bot_text <> 'Description';
UPDATE r5boilertexts SET bot_text = 'com_code' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_QUERY_WOCSUP_COM_CODE' AND bot_lang = 'EN' and  bot_text <> 'com_code';
UPDATE r5boilertexts SET bot_text = 'com_desc' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_QUERY_WOCSUP_COM_DESC' AND bot_lang = 'EN' and  bot_text <> 'com_desc';
UPDATE r5boilertexts SET bot_text = 'com_org' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_QUERY_WOCSUP_COM_ORG' AND bot_lang = 'EN' and  bot_text <> 'com_org';
UPDATE r5boilertexts SET bot_text = 'Lijstweergave' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'LST' AND bot_lang = 'NL' and  bot_text <> 'Lijstweergave';
UPDATE r5boilertexts SET bot_text = 'Omschrijving' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_DESCRIPTION' AND bot_lang = 'NL' and  bot_text <> 'Omschrijving';
UPDATE r5boilertexts SET bot_text = 'Reeks nummer' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_SEQ' AND bot_lang = 'NL' and  bot_text <> 'Reeks nummer';
UPDATE r5boilertexts SET bot_text = 'Organisatie' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_ORG' AND bot_lang = 'NL' and  bot_text <> 'Organisatie';
UPDATE r5boilertexts SET bot_text = 'Onderhoudspartij' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_VEN' AND bot_lang = 'NL' and  bot_text <> 'Onderhoudspartij';
UPDATE r5boilertexts SET bot_text = 'Statuswaarden' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_STATUS' AND bot_lang = 'NL' and  bot_text <> 'Statuswaarden';
UPDATE r5boilertexts SET bot_text = 'Status Omschrijving' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_STADESC' AND bot_lang = 'NL' and  bot_text <> 'Status Omschrijving';
UPDATE r5boilertexts SET bot_text = 'IO datum gegenereerd' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_DATEGEN' AND bot_lang = 'NL' and  bot_text <> 'IO datum gegenereerd';
UPDATE r5boilertexts SET bot_text = 'Aangemaakt door' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_WCCREATEDBY' AND bot_lang = 'NL' and  bot_text <> 'Aangemaakt door';
UPDATE r5boilertexts SET bot_text = 'Datum aangemaakt' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_WCCREATED' AND bot_lang = 'NL' and  bot_text <> 'Datum aangemaakt';
UPDATE r5boilertexts SET bot_text = 'IO gegenereerd door' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_POCREATEDBY' AND bot_lang = 'NL' and  bot_text <> 'IO gegenereerd door';
UPDATE r5boilertexts SET bot_text = 'Inkoop order' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_PO' AND bot_lang = 'NL' and  bot_text <> 'Inkoop order';
UPDATE r5boilertexts SET bot_text = 'Record View' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'HDR' AND bot_lang = 'NL' and  bot_text <> 'Record View';
UPDATE r5boilertexts SET bot_text = 'Details' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'BLOCK_10_1' AND bot_lang = 'NL' and  bot_text <> 'Details';
UPDATE r5boilertexts SET bot_text = '?ProcessUserDefinedScreenService' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'BLOCK_10_2' AND bot_lang = 'NL' and  bot_text <> '?ProcessUserDefinedScreenService';
UPDATE r5boilertexts SET bot_text = '?<SECTION TITLE>' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'BLOCK_10_3' AND bot_lang = 'NL' and  bot_text <> '?<SECTION TITLE>';
UPDATE r5boilertexts SET bot_text = 'Organisatie' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'BLOCK_10_CF' AND bot_lang = 'NL' and  bot_text <> 'Organisatie';
UPDATE r5boilertexts SET bot_text = '?<SECTION TITLE>' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'BLOCK_10_4' AND bot_lang = 'NL' and  bot_text <> '?<SECTION TITLE>';
UPDATE r5boilertexts SET bot_text = '?<SECTION TITLE>' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'BLOCK_10_5' AND bot_lang = 'NL' and  bot_text <> '?<SECTION TITLE>';
UPDATE r5boilertexts SET bot_text = '?<SECTION TITLE>' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'BLOCK_10_6' AND bot_lang = 'NL' and  bot_text <> '?<SECTION TITLE>';
UPDATE r5boilertexts SET bot_text = 'Inkooporder details' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'BLOCK_10_7' AND bot_lang = 'NL' and  bot_text <> 'Inkooporder details';
UPDATE r5boilertexts SET bot_text = 'Bevestigen' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'GWPSUBMITBUTTON' AND bot_lang = 'NL' and  bot_text <> 'Bevestigen';
UPDATE r5boilertexts SET bot_text = 'Wissen' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'GWPCLEARBUTTON' AND bot_lang = 'NL' and  bot_text <> 'Wissen';
UPDATE r5boilertexts SET bot_text = 'Omschrijving' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_DESCRIPTION' AND bot_lang = 'NL' and  bot_text <> 'Omschrijving';
UPDATE r5boilertexts SET bot_text = 'Reeks nummer' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_SEQ' AND bot_lang = 'NL' and  bot_text <> 'Reeks nummer';
UPDATE r5boilertexts SET bot_text = 'Organisatie' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_ORG' AND bot_lang = 'NL' and  bot_text <> 'Organisatie';
UPDATE r5boilertexts SET bot_text = 'Onderhoudspartij' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_VEN' AND bot_lang = 'NL' and  bot_text <> 'Onderhoudspartij';
UPDATE r5boilertexts SET bot_text = 'Statuswaarden' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_STATUS' AND bot_lang = 'NL' and  bot_text <> 'Statuswaarden';
UPDATE r5boilertexts SET bot_text = 'Status Omschrijving' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_STADESC' AND bot_lang = 'NL' and  bot_text <> 'Status Omschrijving';
UPDATE r5boilertexts SET bot_text = 'IO datum gegenereerd' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_DATEGEN' AND bot_lang = 'NL' and  bot_text <> 'IO datum gegenereerd';
UPDATE r5boilertexts SET bot_text = 'Aangemaakt door' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_WCCREATEDBY' AND bot_lang = 'NL' and  bot_text <> 'Aangemaakt door';
UPDATE r5boilertexts SET bot_text = 'Datum aangemaakt' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_WCCREATED' AND bot_lang = 'NL' and  bot_text <> 'Datum aangemaakt';
UPDATE r5boilertexts SET bot_text = 'IO gegenereerd door' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_POCREATEDBY' AND bot_lang = 'NL' and  bot_text <> 'IO gegenereerd door';
UPDATE r5boilertexts SET bot_text = 'Inkoop order' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_10_CTL_PO' AND bot_lang = 'NL' and  bot_text <> 'Inkoop order';
UPDATE r5boilertexts SET bot_text = 'Opmerkingen' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'CMT' AND bot_lang = 'NL' and  bot_text <> 'Opmerkingen';
UPDATE r5boilertexts SET bot_text = 'Documenten' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'DOC' AND bot_lang = 'NL' and  bot_text <> 'Documenten';
UPDATE r5boilertexts SET bot_text = 'Document toevoegen' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'DOC_ADDNEW' AND bot_lang = 'NL' and  bot_text <> 'Document toevoegen';
UPDATE r5boilertexts SET bot_text = 'Document aanmaken/uploaden' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'DOC_CREATEORUPLOADDOCUMENT' AND bot_lang = 'NL' and  bot_text <> 'Document aanmaken/uploaden';
UPDATE r5boilertexts SET bot_text = 'Document uploaden' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'DOC_UPLOADDOCUMENT' AND bot_lang = 'NL' and  bot_text <> 'Document uploaden';
UPDATE r5boilertexts SET bot_text = 'Document aanmaken' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'DOC_CREATEDOCUMENT' AND bot_lang = 'NL' and  bot_text <> 'Document aanmaken';
UPDATE r5boilertexts SET bot_text = 'Documenten' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'DOC_DOCDETAILS' AND bot_lang = 'NL' and  bot_text <> 'Documenten';
UPDATE r5boilertexts SET bot_text = 'Work Order Check' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'XWO' AND bot_lang = 'NL' and  bot_text <> 'Work Order Check';
UPDATE r5boilertexts SET bot_text = 'Work Order Check' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'XWO_HDRLABEL' AND bot_lang = 'NL' and  bot_text <> 'Work Order Check';
UPDATE r5boilertexts SET bot_text = 'All Records' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'XWO_DSNAME' AND bot_lang = 'NL' and  bot_text <> 'All Records';
UPDATE r5boilertexts SET bot_text = 'Work Order' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'xwo_evtcode' AND bot_lang = 'NL' and  bot_text <> 'Work Order';
UPDATE r5boilertexts SET bot_text = 'Work Order Desc' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'xwo_evtdesc' AND bot_lang = 'NL' and  bot_text <> 'Work Order Desc';
UPDATE r5boilertexts SET bot_text = 'Asset' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'xwo_evtobject' AND bot_lang = 'NL' and  bot_text <> 'Asset';
UPDATE r5boilertexts SET bot_text = 'Licence Plate' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'xwo_objalias' AND bot_lang = 'NL' and  bot_text <> 'Licence Plate';
UPDATE r5boilertexts SET bot_text = 'Date Ready' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'xwo_evtudfdate09' AND bot_lang = 'NL' and  bot_text <> 'Date Ready';
UPDATE r5boilertexts SET bot_text = 'Agree' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'xwo_evtudfchkbox02' AND bot_lang = 'NL' and  bot_text <> 'Agree';
UPDATE r5boilertexts SET bot_text = 'Work Order Status' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'xwo_evtstatus' AND bot_lang = 'NL' and  bot_text <> 'Work Order Status';
UPDATE r5boilertexts SET bot_text = 'Asset Desc' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'xwo_objdesc' AND bot_lang = 'NL' and  bot_text <> 'Asset Desc';
UPDATE r5boilertexts SET bot_text = 'Material Cost' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'xwo_matcost' AND bot_lang = 'NL' and  bot_text <> 'Material Cost';
UPDATE r5boilertexts SET bot_text = 'Fixed Cost' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'xwo_fixedcost' AND bot_lang = 'NL' and  bot_text <> 'Fixed Cost';
UPDATE r5boilertexts SET bot_text = 'Cost Hours' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'xwo_costhours' AND bot_lang = 'NL' and  bot_text <> 'Cost Hours';
UPDATE r5boilertexts SET bot_text = 'Total Cost' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'xwo_totalcost' AND bot_lang = 'NL' and  bot_text <> 'Total Cost';
UPDATE r5boilertexts SET bot_text = 'Code' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_QUERY_WOCORG_ORG_CODE' AND bot_lang = 'NL' and  bot_text <> 'Code';
UPDATE r5boilertexts SET bot_text = 'Omschrijving' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_QUERY_WOCORG_ORG_DESC' AND bot_lang = 'NL' and  bot_text <> 'Omschrijving';
UPDATE r5boilertexts SET bot_text = '?com_code' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_QUERY_WOCSUP_COM_CODE' AND bot_lang = 'NL' and  bot_text <> '?com_code';
UPDATE r5boilertexts SET bot_text = '?com_desc' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_QUERY_WOCSUP_COM_DESC' AND bot_lang = 'NL' and  bot_text <> '?com_desc';
UPDATE r5boilertexts SET bot_text = '?com_org' WHERE bot_function = 'OUWOCF' AND bot_fld1 = 'WSPF_QUERY_WOCSUP_COM_ORG' AND bot_lang = 'NL' and  bot_text <> '?com_org';

PROMPT ...End of Boilertexts:OUWOCF

COMMIT;
SET DEFINE ON;

PROMPT
PROMPT ...End of qbz_uds_ouwocf_bot.sql