-- -------------------------------------------------------------------------------
--
-- Copyright © 2020 by Spectades BV
--
-- Filename    : qbz_uds_schade_plo.sql
--
-- Description : Configure pagelayout for SCHADE
--
-- Product     : EAM             Release : 11.7          Build :
--
-- Author      : MCT
--
-- CHANGE HISTORY
--
-- 0001 02-12-2022  - MCT - SPC295  - Creation
-- -------------------------------------------------------------------------------

PROMPT ...Begin of qbz_uds_schade_plo.sql

SET DEFINE OFF;

PROMPT ...Delete all SCHADE_U1 pagelayout
DELETE FROM r5pagelayout WHERE plo_pagename LIKE 'SCHADE_U1';

PROMPT ...INSERTING into R5PAGELAYOUT
INSERT INTO r5pagelayout(plo_usergroup, plo_pagename, plo_elementid, plo_elementtype, plo_presentinjsp, plo_attribute, plo_fieldcontainer, plo_fieldgroup, plo_positioningroup, plo_fieldconttype, plo_tabindex, plo_systemattribute, plo_changed, plo_updatecount, plo_mekey, plo_meflag, plo_defaultvalue, plo_parentpage, plo_lastsaved) VALUES('R5','SCHADE_U1','SCHADE_U1','G','Y','O',NULL,NULL,NULL,NULL,NULL,'O','-',0,'YY','E',NULL,NULL,SYSDATE);
INSERT INTO r5pagelayout(plo_usergroup, plo_pagename, plo_elementid, plo_elementtype, plo_presentinjsp, plo_attribute, plo_fieldcontainer, plo_fieldgroup, plo_positioningroup, plo_fieldconttype, plo_tabindex, plo_systemattribute, plo_changed, plo_updatecount, plo_mekey, plo_meflag, plo_defaultvalue, plo_parentpage, plo_lastsaved) VALUES('R5','SCHADE_U1','block_10_1','B','Y','O',NULL,NULL,NULL,NULL,NULL,'O','-',0,'YY','E',NULL,NULL,SYSDATE);
INSERT INTO r5pagelayout(plo_usergroup, plo_pagename, plo_elementid, plo_elementtype, plo_presentinjsp, plo_attribute, plo_fieldcontainer, plo_fieldgroup, plo_positioningroup, plo_fieldconttype, plo_tabindex, plo_systemattribute, plo_changed, plo_updatecount, plo_mekey, plo_meflag, plo_defaultvalue, plo_parentpage, plo_lastsaved) VALUES('R5','SCHADE_U1','block_10_2','B','Y','O',NULL,NULL,NULL,NULL,NULL,'O','-',0,'YY','E',NULL,NULL,SYSDATE);
INSERT INTO r5pagelayout(plo_usergroup, plo_pagename, plo_elementid, plo_elementtype, plo_presentinjsp, plo_attribute, plo_fieldcontainer, plo_fieldgroup, plo_positioningroup, plo_fieldconttype, plo_tabindex, plo_systemattribute, plo_changed, plo_updatecount, plo_mekey, plo_meflag, plo_defaultvalue, plo_parentpage, plo_lastsaved) VALUES('R5','SCHADE_U1','block_10_3','B','Y','H',NULL,NULL,NULL,NULL,NULL,'O','-',0,'YY','E',NULL,NULL,SYSDATE);
INSERT INTO r5pagelayout(plo_usergroup, plo_pagename, plo_elementid, plo_elementtype, plo_presentinjsp, plo_attribute, plo_fieldcontainer, plo_fieldgroup, plo_positioningroup, plo_fieldconttype, plo_tabindex, plo_systemattribute, plo_changed, plo_updatecount, plo_mekey, plo_meflag, plo_defaultvalue, plo_parentpage, plo_lastsaved) VALUES('R5','SCHADE_U1','block_10_4','B','Y','H',NULL,NULL,NULL,NULL,NULL,'O','-',0,'YY','E',NULL,NULL,SYSDATE);
INSERT INTO r5pagelayout(plo_usergroup, plo_pagename, plo_elementid, plo_elementtype, plo_presentinjsp, plo_attribute, plo_fieldcontainer, plo_fieldgroup, plo_positioningroup, plo_fieldconttype, plo_tabindex, plo_systemattribute, plo_changed, plo_updatecount, plo_mekey, plo_meflag, plo_defaultvalue, plo_parentpage, plo_lastsaved) VALUES('R5','SCHADE_U1','block_10_5','B','Y','H',NULL,NULL,NULL,NULL,NULL,'O','-',0,'YY','E',NULL,NULL,SYSDATE);
INSERT INTO r5pagelayout(plo_usergroup, plo_pagename, plo_elementid, plo_elementtype, plo_presentinjsp, plo_attribute, plo_fieldcontainer, plo_fieldgroup, plo_positioningroup, plo_fieldconttype, plo_tabindex, plo_systemattribute, plo_changed, plo_updatecount, plo_mekey, plo_meflag, plo_defaultvalue, plo_parentpage, plo_lastsaved) VALUES('R5','SCHADE_U1','block_10_6','B','Y','H',NULL,NULL,NULL,NULL,NULL,'O','-',0,'YY','E',NULL,NULL,SYSDATE);
INSERT INTO r5pagelayout(plo_usergroup, plo_pagename, plo_elementid, plo_elementtype, plo_presentinjsp, plo_attribute, plo_fieldcontainer, plo_fieldgroup, plo_positioningroup, plo_fieldconttype, plo_tabindex, plo_systemattribute, plo_changed, plo_updatecount, plo_mekey, plo_meflag, plo_defaultvalue, plo_parentpage, plo_lastsaved) VALUES('R5','SCHADE_U1','block_10_7','B','Y','H',NULL,NULL,NULL,NULL,NULL,'O','-',0,'YY','E',NULL,NULL,SYSDATE);
INSERT INTO r5pagelayout(plo_usergroup, plo_pagename, plo_elementid, plo_elementtype, plo_presentinjsp, plo_attribute, plo_fieldcontainer, plo_fieldgroup, plo_positioningroup, plo_fieldconttype, plo_tabindex, plo_systemattribute, plo_changed, plo_updatecount, plo_mekey, plo_meflag, plo_defaultvalue, plo_parentpage, plo_lastsaved) VALUES('R5','SCHADE_U1','clear','LB','Y','O',NULL,NULL,NULL,NULL,NULL,'O','-',0,'YY','E',NULL,NULL,SYSDATE);
INSERT INTO r5pagelayout(plo_usergroup, plo_pagename, plo_elementid, plo_elementtype, plo_presentinjsp, plo_attribute, plo_fieldcontainer, plo_fieldgroup, plo_positioningroup, plo_fieldconttype, plo_tabindex, plo_systemattribute, plo_changed, plo_updatecount, plo_mekey, plo_meflag, plo_defaultvalue, plo_parentpage, plo_lastsaved) VALUES('R5','SCHADE_U1','delete','LB','Y','O',NULL,NULL,NULL,NULL,NULL,'O','-',0,'YY','E',NULL,NULL,SYSDATE);
INSERT INTO r5pagelayout(plo_usergroup, plo_pagename, plo_elementid, plo_elementtype, plo_presentinjsp, plo_attribute, plo_fieldcontainer, plo_fieldgroup, plo_positioningroup, plo_fieldconttype, plo_tabindex, plo_systemattribute, plo_changed, plo_updatecount, plo_mekey, plo_meflag, plo_defaultvalue, plo_parentpage, plo_lastsaved) VALUES('R5','SCHADE_U1','new','LB','Y','O',NULL,NULL,NULL,NULL,NULL,'O','-',0,'YY','E',NULL,NULL,SYSDATE);
INSERT INTO r5pagelayout(plo_usergroup, plo_pagename, plo_elementid, plo_elementtype, plo_presentinjsp, plo_attribute, plo_fieldcontainer, plo_fieldgroup, plo_positioningroup, plo_fieldconttype, plo_tabindex, plo_systemattribute, plo_changed, plo_updatecount, plo_mekey, plo_meflag, plo_defaultvalue, plo_parentpage, plo_lastsaved) VALUES('R5','SCHADE_U1','submit','LB','Y','O',NULL,NULL,NULL,NULL,NULL,'O','-',0,'YY','E',NULL,NULL,SYSDATE);
INSERT INTO r5pagelayout(plo_usergroup, plo_pagename, plo_elementid, plo_elementtype, plo_presentinjsp, plo_attribute, plo_fieldcontainer, plo_fieldgroup, plo_positioningroup, plo_fieldconttype, plo_tabindex, plo_systemattribute, plo_changed, plo_updatecount, plo_mekey, plo_meflag, plo_defaultvalue, plo_parentpage, plo_lastsaved) VALUES('R5','SCHADE_U1','wspf_10_cos_afas','F','Y','O','cont_1',2,1,2,20,'O','-',0,'YY','E',NULL,NULL,SYSDATE);
INSERT INTO r5pagelayout(plo_usergroup, plo_pagename, plo_elementid, plo_elementtype, plo_presentinjsp, plo_attribute, plo_fieldcontainer, plo_fieldgroup, plo_positioningroup, plo_fieldconttype, plo_tabindex, plo_systemattribute, plo_changed, plo_updatecount, plo_mekey, plo_meflag, plo_defaultvalue, plo_parentpage, plo_lastsaved) VALUES('R5','SCHADE_U1','wspf_10_cos_case','F','Y','P','cont_2',1,1,1,40,'R','-',0,'YY','E',NULL,NULL,SYSDATE);
INSERT INTO r5pagelayout(plo_usergroup, plo_pagename, plo_elementid, plo_elementtype, plo_presentinjsp, plo_attribute, plo_fieldcontainer, plo_fieldgroup, plo_positioningroup, plo_fieldconttype, plo_tabindex, plo_systemattribute, plo_changed, plo_updatecount, plo_mekey, plo_meflag, plo_defaultvalue, plo_parentpage, plo_lastsaved) VALUES('R5','SCHADE_U1','wspf_10_cos_cost','F','Y','O','cont_3',2,1,1,80,'O','-',0,'YY','E',NULL,NULL,SYSDATE);
INSERT INTO r5pagelayout(plo_usergroup, plo_pagename, plo_elementid, plo_elementtype, plo_presentinjsp, plo_attribute, plo_fieldcontainer, plo_fieldgroup, plo_positioningroup, plo_fieldconttype, plo_tabindex, plo_systemattribute, plo_changed, plo_updatecount, plo_mekey, plo_meflag, plo_defaultvalue, plo_parentpage, plo_lastsaved) VALUES('R5','SCHADE_U1','wspf_10_cos_costcode','F','Y','R','cont_3',1,1,1,70,'R','-',0,'YY','E',NULL,NULL,SYSDATE);
INSERT INTO r5pagelayout(plo_usergroup, plo_pagename, plo_elementid, plo_elementtype, plo_presentinjsp, plo_attribute, plo_fieldcontainer, plo_fieldgroup, plo_positioningroup, plo_fieldconttype, plo_tabindex, plo_systemattribute, plo_changed, plo_updatecount, plo_mekey, plo_meflag, plo_defaultvalue, plo_parentpage, plo_lastsaved) VALUES('R5','SCHADE_U1','wspf_10_cos_costcodedesc','F','Y','O','cont_1',3,1,2,30,'O','-',0,'YY',NULL,NULL,NULL,SYSDATE);
INSERT INTO r5pagelayout(plo_usergroup, plo_pagename, plo_elementid, plo_elementtype, plo_presentinjsp, plo_attribute, plo_fieldcontainer, plo_fieldgroup, plo_positioningroup, plo_fieldconttype, plo_tabindex, plo_systemattribute, plo_changed, plo_updatecount, plo_mekey, plo_meflag, plo_defaultvalue, plo_parentpage, plo_lastsaved) VALUES('R5','SCHADE_U1','wspf_10_cos_costdesc','F','Y','R','cont_1',1,1,2,10,'R','-',0,'YY','E',NULL,NULL,SYSDATE);
INSERT INTO r5pagelayout(plo_usergroup, plo_pagename, plo_elementid, plo_elementtype, plo_presentinjsp, plo_attribute, plo_fieldcontainer, plo_fieldgroup, plo_positioningroup, plo_fieldconttype, plo_tabindex, plo_systemattribute, plo_changed, plo_updatecount, plo_mekey, plo_meflag, plo_defaultvalue, plo_parentpage, plo_lastsaved) VALUES('R5','SCHADE_U1','wspf_10_cos_date','F','Y','O','cont_2',3,1,1,60,'O','-',0,'YY','E',NULL,NULL,SYSDATE);
INSERT INTO r5pagelayout(plo_usergroup, plo_pagename, plo_elementid, plo_elementtype, plo_presentinjsp, plo_attribute, plo_fieldcontainer, plo_fieldgroup, plo_positioningroup, plo_fieldconttype, plo_tabindex, plo_systemattribute, plo_changed, plo_updatecount, plo_mekey, plo_meflag, plo_defaultvalue, plo_parentpage, plo_lastsaved) VALUES('R5','SCHADE_U1','wspf_10_cos_line','F','Y','P','cont_2',2,1,1,50,'R','-',0,'YY','E',NULL,NULL,SYSDATE);
INSERT INTO r5pagelayout(plo_usergroup, plo_pagename, plo_elementid, plo_elementtype, plo_presentinjsp, plo_attribute, plo_fieldcontainer, plo_fieldgroup, plo_positioningroup, plo_fieldconttype, plo_tabindex, plo_systemattribute, plo_changed, plo_updatecount, plo_mekey, plo_meflag, plo_defaultvalue, plo_parentpage, plo_lastsaved) VALUES('R5','SCHADE_U1','wspf_10_cos_totalcost','F','Y','P','cont_3',3,1,1,90,'O','-',0,'YY','E',NULL,NULL,SYSDATE);
INSERT INTO r5pagelayout(plo_usergroup, plo_pagename, plo_elementid, plo_elementtype, plo_presentinjsp, plo_attribute, plo_fieldcontainer, plo_fieldgroup, plo_positioningroup, plo_fieldconttype, plo_tabindex, plo_systemattribute, plo_changed, plo_updatecount, plo_mekey, plo_meflag, plo_defaultvalue, plo_parentpage, plo_lastsaved) VALUES('R5','SCHADE_U1','wspf_10_cos_wo','F','Y','H','cont_3',4,1,1,100,'O','-',0,'YY',NULL,NULL,NULL,SYSDATE);
COMMIT;

PROMPT Copy pagelayout from R5 to all other groups
INSERT INTO r5pagelayout
(plo_usergroup,plo_pagename,plo_elementid,plo_elementtype,plo_presentinjsp,plo_attribute,plo_fieldcontainer,plo_fieldgroup,plo_positioningroup,plo_fieldconttype,plo_tabindex,plo_systemattribute,plo_changed,plo_updatecount,plo_mekey,plo_meflag,plo_defaultvalue,plo_parentpage,plo_lastsaved)
SELECT ugr_code plo_usergroup,plo_pagename,plo_elementid,plo_elementtype,plo_presentinjsp,plo_attribute,plo_fieldcontainer,plo_fieldgroup,plo_positioningroup,plo_fieldconttype,plo_tabindex,plo_systemattribute,plo_changed,plo_updatecount,plo_mekey,plo_meflag,plo_defaultvalue,plo_parentpage,plo_lastsaved
FROM r5groups, r5pagelayout
WHERE plo_pagename LIKE 'SCHADE_U1'
AND plo_usergroup = 'R5'
AND ugr_code <> 'R5';

COMMIT;

PROMPT ...End of Pagelayout: SCHADE_U1

PROMPT ...Updating Pagelayout for: SCHADE
UPDATE r5pagelayout SET plo_attribute = 'H' WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'block_11';
UPDATE r5pagelayout SET plo_attribute = 'H' WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'block_3';
UPDATE r5pagelayout SET plo_attribute = 'H' WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'block_4';
UPDATE r5pagelayout SET plo_attribute = 'H' WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'block_6';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_15',plo_fieldgroup = 1,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1840,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfchar29';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_15',plo_fieldgroup = 3,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1860,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfchkbox03';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_15',plo_fieldgroup = 4,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1870,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfchkbox05';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_16',plo_fieldgroup = 1,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1880,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfchar28';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_16',plo_fieldgroup = 2,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1890,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfnum05';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_16.5',plo_fieldgroup = 1,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1900,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfnote02';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_10',plo_fieldgroup = 7,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 750,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'inspectiondirection';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_10',plo_fieldgroup = 8,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 760,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'flow';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_11',plo_fieldgroup = 6,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 820,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'wodescription';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_12',plo_fieldgroup = 1,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 830,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'standardwo';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_12',plo_fieldgroup = 2,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 840,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'wotype';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_12',plo_fieldgroup = 3,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 850,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'woclass';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_12',plo_fieldgroup = 4,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 860,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'woclassorg';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_12',plo_fieldgroup = 5,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 870,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'wostatus';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_12',plo_fieldgroup = 6,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 880,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'wopriority';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_13',plo_fieldgroup = 1,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 890,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'taskplan';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_13',plo_fieldgroup = 2,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 900,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'jobplan';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_13',plo_fieldgroup = 3,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 910,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'trade';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_13',plo_fieldgroup = 4,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 920,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'esthours';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_13',plo_fieldgroup = 5,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 930,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'pplreq';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_13',plo_fieldgroup = 6,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 940,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'followupwo';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_14',plo_fieldgroup = 10,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1040,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'assignedtoemail';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_14',plo_fieldgroup = 13,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1070,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'reqstartdate';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_14',plo_fieldgroup = 14,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1080,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'reqenddate';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_14',plo_fieldgroup = 15,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1090,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'startdate';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_14',plo_fieldgroup = 16,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1100,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'completed';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_14',plo_fieldgroup = 17,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1110,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'incidentrequest';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_14',plo_fieldgroup = 18,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1120,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'incidentrequestorg';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_14',plo_fieldgroup = 19,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1130,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'incidentrequeststatus';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_14',plo_fieldgroup = 20,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1140,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'sourcetype';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_14',plo_fieldgroup = 6,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1000,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'preparedby';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_14',plo_fieldgroup = 7,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1010,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'preparedbyname';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_14',plo_fieldgroup = 8,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1020,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'preparedbyemail';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_14',plo_fieldgroup = 9,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1030,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'assignedtoname';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_17',plo_fieldgroup = 1,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1910,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'createfollowupwo';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_17',plo_fieldgroup = 2,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1920,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'refreshcostdata';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_17',plo_fieldgroup = 3,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1930,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'translatewodescription';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_2',plo_fieldgroup = 1,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 10,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'equipmentorg';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_2',plo_fieldgroup = 7,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 70,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'updatedby';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_4',plo_fieldgroup = 10,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 270,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'esignaturedate';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_4',plo_fieldgroup = 11,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 280,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'esignaturetype';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_4',plo_fieldgroup = 9,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 260,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'esignature';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_5',plo_fieldgroup = 1,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 290,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'class';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_6',plo_fieldgroup = 1,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 300,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'classorg';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_7',plo_fieldgroup = 1,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 310,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'location';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_7',plo_fieldgroup = 1,plo_positioningroup = 2,plo_fieldconttype = 1,plo_tabindex = 320,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'locationdesc';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_7',plo_fieldgroup = 2,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 330,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'servicecode';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_7',plo_fieldgroup = 2,plo_positioningroup = 2,plo_fieldconttype = 1,plo_tabindex = 340,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'servicecodedesc';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_7',plo_fieldgroup = 3,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 350,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'workaddress';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_8',plo_fieldgroup = 1,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 360,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'servicecodeorg';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_8',plo_fieldgroup = 10,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 450,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'eventenddate';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_8',plo_fieldgroup = 11,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 460,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'totalestimatedcosts';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_8',plo_fieldgroup = 11,plo_positioningroup = 2,plo_fieldconttype = 1,plo_tabindex = 470,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'totalestimatedcosts_curr';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_8',plo_fieldgroup = 12,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 480,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'totalcalculatedcosts';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_8',plo_fieldgroup = 12,plo_positioningroup = 2,plo_fieldconttype = 1,plo_tabindex = 490,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'totalcalculatedcosts_curr';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_8',plo_fieldgroup = 2,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 370,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'locationorg';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_8',plo_fieldgroup = 3,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 380,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'costcode';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_8',plo_fieldgroup = 8,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 430,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'priority';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_8',plo_fieldgroup = 9,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 440,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'eventstartdate';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_9',plo_fieldgroup = 1,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 500,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'permittowork';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_9',plo_fieldgroup = 10,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 590,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'shift';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_9',plo_fieldgroup = 11,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 600,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'project';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_9',plo_fieldgroup = 12,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 610,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'campaign';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_9',plo_fieldgroup = 13,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 620,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'parent';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_9',plo_fieldgroup = 14,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 630,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'regulatory';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_9',plo_fieldgroup = 15,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 640,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'followuprequired';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_9',plo_fieldgroup = 16,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 650,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'hazardousmaterial';
UPDATE r5pagelayout SET plo_attribute = 'H',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_9',plo_fieldgroup = 17,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 660,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'refreshcalculatedcosts';
UPDATE r5pagelayout SET plo_attribute = 'O' WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'block_1';
UPDATE r5pagelayout SET plo_attribute = 'O' WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'block_10';
UPDATE r5pagelayout SET plo_attribute = 'O' WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'block_2';
UPDATE r5pagelayout SET plo_attribute = 'O' WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'block_5';
UPDATE r5pagelayout SET plo_attribute = 'O' WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'block_7';
UPDATE r5pagelayout SET plo_attribute = 'O' WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'block_8';
UPDATE r5pagelayout SET plo_attribute = 'O' WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'block_9';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.1',plo_fieldgroup = 4,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1180,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'problemdesc';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.1',plo_fieldgroup = 5,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1190,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'whathappened';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.2',plo_fieldgroup = 1,plo_positioningroup = 1,plo_fieldconttype = 2,plo_tabindex = 1200,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'downtimecost';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.2',plo_fieldgroup = 2,plo_positioningroup = 1,plo_fieldconttype = 2,plo_tabindex = 1220,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'totalcost';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.3',plo_fieldgroup = 1,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1240,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'downtimehours';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.3',plo_fieldgroup = 2,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1250,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'lostproductivityhours';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.4',plo_fieldgroup = 1,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1260,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'why1';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.4',plo_fieldgroup = 2,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1270,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'why2';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.4',plo_fieldgroup = 3,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1280,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'why3';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.4',plo_fieldgroup = 4,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1290,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'why4';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.4',plo_fieldgroup = 5,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1300,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'why5';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.4',plo_fieldgroup = 6,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1310,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'solution';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.7',plo_fieldgroup = 10,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1450,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'actioncode';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.7',plo_fieldgroup = 11,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1460,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'causecode';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.7',plo_fieldgroup = 12,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1470,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'failuremodedesc';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.7',plo_fieldgroup = 8,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1430,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'symptom';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.7',plo_fieldgroup = 9,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1440,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'failurecode';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.8',plo_fieldgroup = 10,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1570,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'methodofdetection';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.8',plo_fieldgroup = 6,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1530,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'tacticalcause';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.8',plo_fieldgroup = 7,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1540,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'humanfactor';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.8',plo_fieldgroup = 8,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1550,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'workmanship';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.8',plo_fieldgroup = 9,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1560,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'humanoversight';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_4',plo_fieldgroup = 8,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 250,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfchar27';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_10',plo_fieldgroup = 1,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 670,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'frompoint';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_10',plo_fieldgroup = 2,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 690,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'frompointrefdesc';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_10',plo_fieldgroup = 3,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 700,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'frompointgeoref';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_10',plo_fieldgroup = 4,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 710,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'topoint';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_10',plo_fieldgroup = 5,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 730,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'topointrefdesc';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_10',plo_fieldgroup = 6,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 740,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'topointgeoref';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_11',plo_fieldgroup = 1,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 770,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfchar20';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_11',plo_fieldgroup = 2,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 780,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfchar21';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_11',plo_fieldgroup = 3,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 790,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfchar22';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_11',plo_fieldgroup = 4,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 800,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfchkbox01';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_11',plo_fieldgroup = 5,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 810,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfchar23';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_14',plo_fieldgroup = 1,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 950,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'requestedby';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_14',plo_fieldgroup = 11,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1050,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'schedstartdate';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_14',plo_fieldgroup = 12,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1060,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'schedenddate';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_14',plo_fieldgroup = 2,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 960,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'daterequested';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_14',plo_fieldgroup = 3,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 970,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'responsible';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_14',plo_fieldgroup = 4,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 980,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'responsiblename';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_14',plo_fieldgroup = 5,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 990,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'responsibleemail';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_14.1',plo_fieldgroup = 1,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1150,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfchar25';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_14.1',plo_fieldgroup = 2,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1160,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfchar26';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_14.1',plo_fieldgroup = 3,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1170,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfchar24';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_14.7',plo_fieldgroup = 1,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1360,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfnum01';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_14.7',plo_fieldgroup = 2,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1370,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfnum02';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_14.7',plo_fieldgroup = 3,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1380,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfnum03';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_14.7',plo_fieldgroup = 4,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1390,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfchkbox04';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_14.7',plo_fieldgroup = 5,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1400,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfchar14';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_14.7',plo_fieldgroup = 6,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1410,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfchar15';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_14.7',plo_fieldgroup = 7,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1420,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfchar16';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_14.8',plo_fieldgroup = 1,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1480,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfchar18';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_14.8',plo_fieldgroup = 2,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1490,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfdate03';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_14.8',plo_fieldgroup = 3,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1500,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfchar19';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_14.8',plo_fieldgroup = 4,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1510,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfchar17';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_14.8',plo_fieldgroup = 5,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1520,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfdate04';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_15',plo_fieldgroup = 2,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1850,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfnum04';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_2',plo_fieldgroup = 3,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 30,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'assignedto';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_2',plo_fieldgroup = 4,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 40,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfchar02';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_3',plo_fieldgroup = 2,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 110,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'equipment';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_3',plo_fieldgroup = 3,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 130,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfchar01';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_3',plo_fieldgroup = 6,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 160,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfdate05';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_3',plo_fieldgroup = 7,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 170,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'problemcode';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_4',plo_fieldgroup = 2,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 190,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'workorder';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_4',plo_fieldgroup = 4,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 210,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfchar11';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_4',plo_fieldgroup = 5,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 220,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfdate01';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_4',plo_fieldgroup = 6,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 230,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfchar12';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_4',plo_fieldgroup = 7,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 240,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfchkbox02';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_8',plo_fieldgroup = 4,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 390,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'area';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_8',plo_fieldgroup = 5,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 400,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfchar05';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_8',plo_fieldgroup = 6,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 410,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfchar30';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_8',plo_fieldgroup = 7,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 420,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfnote01';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_9',plo_fieldgroup = 2,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 510,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfchar04';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_9',plo_fieldgroup = 3,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 520,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfchar06';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_9',plo_fieldgroup = 8,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 570,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfdate02';
UPDATE r5pagelayout SET plo_attribute = 'O',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_9',plo_fieldgroup = 9,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 580,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfchar13';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.2',plo_fieldgroup = 1,plo_positioningroup = 2,plo_fieldconttype = 2,plo_tabindex = 1210,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'downtimecostcurr';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.2',plo_fieldgroup = 2,plo_positioningroup = 2,plo_fieldconttype = 2,plo_tabindex = 1230,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'totalcostcurr';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.5',plo_fieldgroup = 1,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1320,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'reliabilityproblemcode';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.5',plo_fieldgroup = 2,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1330,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'reliabilityfailurecode';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.6',plo_fieldgroup = 1,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1340,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'reliabilityactioncode';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.6',plo_fieldgroup = 2,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1350,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'reliabilitycausecode';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.9',plo_fieldgroup = 1,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1580,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'eventdate';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.9',plo_fieldgroup = 10,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1670,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'lastlinearslope';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.9',plo_fieldgroup = 11,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1680,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'laplace';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.9',plo_fieldgroup = 12,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1690,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'weibullshape';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.9',plo_fieldgroup = 13,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1700,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'weibullscale';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.9',plo_fieldgroup = 14,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1710,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'weibullcorrelation';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.9',plo_fieldgroup = 15,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1720,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'crowamsaaslope';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.9',plo_fieldgroup = 16,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1730,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'crowamsaaintercept';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.9',plo_fieldgroup = 17,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1740,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'avglinslopecumulativedays';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.9',plo_fieldgroup = 18,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1750,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'lastlinslopecumulativedays';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.9',plo_fieldgroup = 19,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1760,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'weibullshapecumulativedays';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.9',plo_fieldgroup = 2,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1590,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'eventnumber';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.9',plo_fieldgroup = 20,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1770,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'weibullscalecumulativedays';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.9',plo_fieldgroup = 21,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1780,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'weibullcorrcumulativedays';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.9',plo_fieldgroup = 22,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1790,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'crowamsaaslopecumulativedays';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.9',plo_fieldgroup = 23,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1800,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'crowamsaaintcumulativedays';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.9',plo_fieldgroup = 24,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1810,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'crowamsaaslopeiec';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.9',plo_fieldgroup = 25,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1820,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'crowamsaaintiec';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.9',plo_fieldgroup = 26,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1830,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'basedonwo';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.9',plo_fieldgroup = 3,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1600,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'dayssinceprevious';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.9',plo_fieldgroup = 4,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1610,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'cumulativedays';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.9',plo_fieldgroup = 5,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1620,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'meantimebetweenfailure';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.9',plo_fieldgroup = 6,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1630,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'minimumdaysbetween';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.9',plo_fieldgroup = 7,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1640,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'maximumdaysbetween';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.9',plo_fieldgroup = 8,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1650,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'standarddeviation';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'N',plo_fieldcontainer = 'cont_14.9',plo_fieldgroup = 9,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 1660,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'averagelinearslope';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_10',plo_fieldgroup = 1,plo_positioningroup = 2,plo_fieldconttype = 1,plo_tabindex = 680,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'frompointuom';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_10',plo_fieldgroup = 4,plo_positioningroup = 2,plo_fieldconttype = 1,plo_tabindex = 720,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'topointuom';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_2',plo_fieldgroup = 2,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 20,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'createdby';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_2',plo_fieldgroup = 6,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 60,plo_defaultvalue = 'VLOOT' WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'department';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_2',plo_fieldgroup = 8,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 80,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'dateupdated';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_3',plo_fieldgroup = 1,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 90,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'casecode';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_3',plo_fieldgroup = 2,plo_positioningroup = 2,plo_fieldconttype = 1,plo_tabindex = 120,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'equipmentdesc';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_3',plo_fieldgroup = 5,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 150,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'datecreated';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_4',plo_fieldgroup = 1,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 180,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfchar03';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_9',plo_fieldgroup = 4,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 530,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfchar07';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_9',plo_fieldgroup = 5,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 540,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfchar08';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_9',plo_fieldgroup = 6,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 550,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfchar09';
UPDATE r5pagelayout SET plo_attribute = 'P',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_9',plo_fieldgroup = 7,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 560,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'udfchar10';
UPDATE r5pagelayout SET plo_attribute = 'S',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_2',plo_fieldgroup = 5,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 50,plo_defaultvalue = 'SCH' WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'casetype';
UPDATE r5pagelayout SET plo_attribute = 'S',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_3',plo_fieldgroup = 1,plo_positioningroup = 2,plo_fieldconttype = 1,plo_tabindex = 100,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'casedescription';
UPDATE r5pagelayout SET plo_attribute = 'S',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_3',plo_fieldgroup = 4,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 140,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'organization';
UPDATE r5pagelayout SET plo_attribute = 'S',plo_presentinjsp = 'Y',plo_fieldcontainer = 'cont_4',plo_fieldgroup = 3,plo_positioningroup = 1,plo_fieldconttype = 1,plo_tabindex = 200,plo_defaultvalue = NULL WHERE plo_pagename = 'SCHADE' AND plo_elementid = 'status';
COMMIT;
PROMPT ...End of Pagelayout: SCHADE
PROMPT ...End of qbz_uds_schade_plo.sql